# Site specific settings
title: "vr0n"
name: "Website name"
keywords: "tinker, taylor, hacker, spy, hacking, vr0n"
baseurl: "/vr0n.tech/_site"
url: "https://vr0n.tech/"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
encoding: "utf-8"
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
